[project]
name = "src"
version = "0.0.1"
description = "Production-grade ML model management using MLOps."
authors = [{name = "Islam Nabi", email = "islamnabics@gmail.com"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}